 
language: python

sudo: False
dist: trusty

python:
    - 2.7
    - 3.6

install:
    - pip install -U pip
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install -e .

script: skip

after_success: coveralls
